### ISSUE TITLE
node-gyp installation troubles

### ISSUE THREAD

**Issue by PeterKnight** [bengotow/electron-RxDB#4]
I'm on Windows 10 x64 with python 2.7 and windows build tools installed and I've been trying to get this package working but the installation keeps choking around better-sqlite3 and node-gyp. I've gotten as far as the post-install script steps but now get an invalid version number error:

```
gyp ERR! configure error
gyp ERR! stack Error: Invalid version number: latest
gyp ERR! stack     at getNodeDir (C:\Users\PPPP\Local Sites\my-electron-apps\my-project\node_modules\node-gyp\lib\configure.js:72:25)
gyp ERR! stack     at PythonFinder.callback (C:\Users\PPPP\Local Sites\my-electron-apps\my-project\node_modules\node-gyp\lib\configure.js:44:7)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\PPPP\Local Sites\my-electron-apps\my-project\node_modules\node-gyp\lib\configure.js:470:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:244:7)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:887:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PPPP\\Local Sites\\my-electron-apps\\my-project\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "rebuild" "--msvs_version=2013" "--target=latest" "--arch=ia32" "--target_platform=win32" "--dist-url=https://atom.io/download/electron"
gyp ERR! cwd C:\Users\PPPP\Local Sites\my-electron-apps\my-project\node_modules\better-sqlite3
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```
Any ideas on how to resolve? 

Or is there any alternative to depending on node-gyp and/or better-sqlite3? Rxdb in an electron / nuxt.js project is my intended use case.

**Comment by PeterKnight** [comment]
Righto, I fixed the installation error. It didn't like that I had specified my electron package with version set to 'latest' rather than a specific version number. Might help out someone else if they run into this issue.
